//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Wikiled.Dictionary.Legacy.Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WikiledModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WikiledModelContainer object using the connection string found in the 'WikiledModelContainer' section of the application configuration file.
        /// </summary>
        public WikiledModelContainer() : base("name=WikiledModelContainer", "WikiledModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WikiledModelContainer object.
        /// </summary>
        public WikiledModelContainer(string connectionString) : base(connectionString, "WikiledModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WikiledModelContainer object.
        /// </summary>
        public WikiledModelContainer(EntityConnection connection) : base(connection, "WikiledModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<English> Englishes
        {
            get
            {
                if ((_Englishes == null))
                {
                    _Englishes = base.CreateObjectSet<English>("Englishes");
                }
                return _Englishes;
            }
        }
        private ObjectSet<English> _Englishes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AllWord> AllWords
        {
            get
            {
                if ((_AllWords == null))
                {
                    _AllWords = base.CreateObjectSet<AllWord>("AllWords");
                }
                return _AllWords;
            }
        }
        private ObjectSet<AllWord> _AllWords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InfoTable> InfoTable
        {
            get
            {
                if ((_InfoTable == null))
                {
                    _InfoTable = base.CreateObjectSet<InfoTable>("InfoTable");
                }
                return _InfoTable;
            }
        }
        private ObjectSet<InfoTable> _InfoTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rating> Rating
        {
            get
            {
                if ((_Rating == null))
                {
                    _Rating = base.CreateObjectSet<Rating>("Rating");
                }
                return _Rating;
            }
        }
        private ObjectSet<Rating> _Rating;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GoogleTranslation> GoogleTranslation
        {
            get
            {
                if ((_GoogleTranslation == null))
                {
                    _GoogleTranslation = base.CreateObjectSet<GoogleTranslation>("GoogleTranslation");
                }
                return _GoogleTranslation;
            }
        }
        private ObjectSet<GoogleTranslation> _GoogleTranslation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Languages> Languages
        {
            get
            {
                if ((_Languages == null))
                {
                    _Languages = base.CreateObjectSet<Languages>("Languages");
                }
                return _Languages;
            }
        }
        private ObjectSet<Languages> _Languages;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Englishes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEnglishes(English english)
        {
            base.AddObject("Englishes", english);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AllWords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAllWords(AllWord allWord)
        {
            base.AddObject("AllWords", allWord);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InfoTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInfoTable(InfoTable infoTable)
        {
            base.AddObject("InfoTable", infoTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rating EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRating(Rating rating)
        {
            base.AddObject("Rating", rating);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GoogleTranslation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGoogleTranslation(GoogleTranslation googleTranslation)
        {
            base.AddObject("GoogleTranslation", googleTranslation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Languages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLanguages(Languages languages)
        {
            base.AddObject("Languages", languages);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="word">No Metadata Documentation available.</param>
        /// <param name="total">No Metadata Documentation available.</param>
        public ObjectResult<AllWord> GetWords(global::System.String word, Nullable<global::System.Int16> total)
        {
            ObjectParameter wordParameter;
            if (word != null)
            {
                wordParameter = new ObjectParameter("Word", word);
            }
            else
            {
                wordParameter = new ObjectParameter("Word", typeof(global::System.String));
            }
    
            ObjectParameter totalParameter;
            if (total.HasValue)
            {
                totalParameter = new ObjectParameter("Total", total);
            }
            else
            {
                totalParameter = new ObjectParameter("Total", typeof(global::System.Int16));
            }
    
            return base.ExecuteFunction<AllWord>("GetWords", wordParameter, totalParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="word">No Metadata Documentation available.</param>
        /// <param name="total">No Metadata Documentation available.</param>
        public ObjectResult<AllWord> GetWords(global::System.String word, Nullable<global::System.Int16> total, MergeOption mergeOption)
        {
            ObjectParameter wordParameter;
            if (word != null)
            {
                wordParameter = new ObjectParameter("Word", word);
            }
            else
            {
                wordParameter = new ObjectParameter("Word", typeof(global::System.String));
            }
    
            ObjectParameter totalParameter;
            if (total.HasValue)
            {
                totalParameter = new ObjectParameter("Total", total);
            }
            else
            {
                totalParameter = new ObjectParameter("Total", typeof(global::System.Int16));
            }
    
            return base.ExecuteFunction<AllWord>("GetWords", mergeOption, wordParameter, totalParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiledModel", Name="AllWord")]
    [Serializable()]
    [DataContract(IsReference=true)]
    public partial class AllWord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AllWord object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="word">Initial value of the Word property.</param>
        /// <param name="language">Initial value of the Language property.</param>
        public static AllWord CreateAllWord(global::System.Int32 id, global::System.String word, global::System.String language)
        {
            AllWord allWord = new AllWord();
            allWord.id = id;
            allWord.Word = word;
            allWord.Language = language;
            return allWord;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                OnWordChanging(value);
                ReportPropertyChanging("Word");
                _Word = StructuralObject.SetValidValue(value, false, "Word");
                ReportPropertyChanged("Word");
                OnWordChanged();
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Language
        {
            get
            {
                return _Language;
            }
            set
            {
                OnLanguageChanging(value);
                ReportPropertyChanging("Language");
                _Language = StructuralObject.SetValidValue(value, false, "Language");
                ReportPropertyChanged("Language");
                OnLanguageChanged();
            }
        }
        private global::System.String _Language;
        partial void OnLanguageChanging(global::System.String value);
        partial void OnLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WordId
        {
            get
            {
                return _WordId;
            }
            set
            {
                OnWordIdChanging(value);
                ReportPropertyChanging("WordId");
                _WordId = StructuralObject.SetValidValue(value, "WordId");
                ReportPropertyChanged("WordId");
                OnWordIdChanged();
            }
        }
        private Nullable<global::System.Int32> _WordId;
        partial void OnWordIdChanging(Nullable<global::System.Int32> value);
        partial void OnWordIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiledModel", Name="English")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class English : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new English object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="word">Initial value of the word property.</param>
        public static English CreateEnglish(global::System.Int32 id, global::System.String word)
        {
            English english = new English();
            english.id = id;
            english.word = word;
            return english;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String word
        {
            get
            {
                return _word;
            }
            set
            {
                OnwordChanging(value);
                ReportPropertyChanging("word");
                _word = StructuralObject.SetValidValue(value, false, "word");
                ReportPropertyChanged("word");
                OnwordChanged();
            }
        }
        private global::System.String _word;
        partial void OnwordChanging(global::System.String value);
        partial void OnwordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pronansation
        {
            get
            {
                return _pronansation;
            }
            set
            {
                OnpronansationChanging(value);
                ReportPropertyChanging("pronansation");
                _pronansation = StructuralObject.SetValidValue(value, true, "pronansation");
                ReportPropertyChanged("pronansation");
                OnpronansationChanged();
            }
        }
        private global::System.String _pronansation;
        partial void OnpronansationChanging(global::System.String value);
        partial void OnpronansationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> GoogleRating
        {
            get
            {
                return _GoogleRating;
            }
            set
            {
                OnGoogleRatingChanging(value);
                ReportPropertyChanging("GoogleRating");
                _GoogleRating = StructuralObject.SetValidValue(value, "GoogleRating");
                ReportPropertyChanged("GoogleRating");
                OnGoogleRatingChanged();
            }
        }
        private Nullable<global::System.Int64> _GoogleRating;
        partial void OnGoogleRatingChanging(Nullable<global::System.Int64> value);
        partial void OnGoogleRatingChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiledModel", Name="GoogleTranslation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GoogleTranslation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GoogleTranslation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fromLanguage">Initial value of the FromLanguage property.</param>
        /// <param name="toLanguage">Initial value of the ToLanguage property.</param>
        /// <param name="word">Initial value of the Word property.</param>
        /// <param name="translation">Initial value of the Translation property.</param>
        /// <param name="processed">Initial value of the Processed property.</param>
        public static GoogleTranslation CreateGoogleTranslation(global::System.Int32 id, global::System.String fromLanguage, global::System.String toLanguage, global::System.String word, global::System.String translation, global::System.Int16 processed)
        {
            GoogleTranslation googleTranslation = new GoogleTranslation();
            googleTranslation.Id = id;
            googleTranslation.FromLanguage = fromLanguage;
            googleTranslation.ToLanguage = toLanguage;
            googleTranslation.Word = word;
            googleTranslation.Translation = translation;
            googleTranslation.Processed = processed;
            return googleTranslation;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, "Id");
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromLanguage
        {
            get
            {
                return _FromLanguage;
            }
            set
            {
                if (_FromLanguage != value)
                {
                    OnFromLanguageChanging(value);
                    ReportPropertyChanging("FromLanguage");
                    _FromLanguage = StructuralObject.SetValidValue(value, false, "FromLanguage");
                    ReportPropertyChanged("FromLanguage");
                    OnFromLanguageChanged();
                }
            }
        }
        private global::System.String _FromLanguage;
        partial void OnFromLanguageChanging(global::System.String value);
        partial void OnFromLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToLanguage
        {
            get
            {
                return _ToLanguage;
            }
            set
            {
                if (_ToLanguage != value)
                {
                    OnToLanguageChanging(value);
                    ReportPropertyChanging("ToLanguage");
                    _ToLanguage = StructuralObject.SetValidValue(value, false, "ToLanguage");
                    ReportPropertyChanged("ToLanguage");
                    OnToLanguageChanged();
                }
            }
        }
        private global::System.String _ToLanguage;
        partial void OnToLanguageChanging(global::System.String value);
        partial void OnToLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                if (_Word != value)
                {
                    OnWordChanging(value);
                    ReportPropertyChanging("Word");
                    _Word = StructuralObject.SetValidValue(value, false, "Word");
                    ReportPropertyChanged("Word");
                    OnWordChanged();
                }
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Translation
        {
            get
            {
                return _Translation;
            }
            set
            {
                OnTranslationChanging(value);
                ReportPropertyChanging("Translation");
                _Translation = StructuralObject.SetValidValue(value, false, "Translation");
                ReportPropertyChanged("Translation");
                OnTranslationChanged();
            }
        }
        private global::System.String _Translation;
        partial void OnTranslationChanging(global::System.String value);
        partial void OnTranslationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Processed
        {
            get
            {
                return _Processed;
            }
            set
            {
                OnProcessedChanging(value);
                ReportPropertyChanging("Processed");
                _Processed = StructuralObject.SetValidValue(value, "Processed");
                ReportPropertyChanged("Processed");
                OnProcessedChanged();
            }
        }
        private global::System.Int16 _Processed;
        partial void OnProcessedChanging(global::System.Int16 value);
        partial void OnProcessedChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiledModel", Name="InfoTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InfoTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InfoTable object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="fromLanguage">Initial value of the FromLanguage property.</param>
        /// <param name="toLanguage">Initial value of the ToLanguage property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        public static InfoTable CreateInfoTable(global::System.Int32 id, global::System.String fromLanguage, global::System.String toLanguage, global::System.Int32 total)
        {
            InfoTable infoTable = new InfoTable();
            infoTable.id = id;
            infoTable.FromLanguage = fromLanguage;
            infoTable.ToLanguage = toLanguage;
            infoTable.Total = total;
            return infoTable;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromLanguage
        {
            get
            {
                return _FromLanguage;
            }
            set
            {
                OnFromLanguageChanging(value);
                ReportPropertyChanging("FromLanguage");
                _FromLanguage = StructuralObject.SetValidValue(value, false, "FromLanguage");
                ReportPropertyChanged("FromLanguage");
                OnFromLanguageChanged();
            }
        }
        private global::System.String _FromLanguage;
        partial void OnFromLanguageChanging(global::System.String value);
        partial void OnFromLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToLanguage
        {
            get
            {
                return _ToLanguage;
            }
            set
            {
                OnToLanguageChanging(value);
                ReportPropertyChanging("ToLanguage");
                _ToLanguage = StructuralObject.SetValidValue(value, false, "ToLanguage");
                ReportPropertyChanged("ToLanguage");
                OnToLanguageChanged();
            }
        }
        private global::System.String _ToLanguage;
        partial void OnToLanguageChanging(global::System.String value);
        partial void OnToLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value, "Total");
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.Int32 _Total;
        partial void OnTotalChanging(global::System.Int32 value);
        partial void OnTotalChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiledModel", Name="Languages")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Languages : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Languages object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="sqlDbType">Initial value of the SqlDbType property.</param>
        /// <param name="language">Initial value of the Language property.</param>
        /// <param name="isLatin">Initial value of the IsLatin property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="joinTable">Initial value of the JoinTable property.</param>
        /// <param name="joinField">Initial value of the JoinField property.</param>
        /// <param name="languageType">Initial value of the LanguageType property.</param>
        public static Languages CreateLanguages(global::System.Int32 id, global::System.Boolean sqlDbType, global::System.String language, global::System.Boolean isLatin, global::System.String name, global::System.String joinTable, global::System.String joinField, global::System.String languageType)
        {
            Languages languages = new Languages();
            languages.id = id;
            languages.SqlDbType = sqlDbType;
            languages.Language = language;
            languages.IsLatin = isLatin;
            languages.Name = name;
            languages.JoinTable = joinTable;
            languages.JoinField = joinField;
            languages.LanguageType = languageType;
            return languages;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SqlDbType
        {
            get
            {
                return _SqlDbType;
            }
            set
            {
                OnSqlDbTypeChanging(value);
                ReportPropertyChanging("SqlDbType");
                _SqlDbType = StructuralObject.SetValidValue(value, "SqlDbType");
                ReportPropertyChanged("SqlDbType");
                OnSqlDbTypeChanged();
            }
        }
        private global::System.Boolean _SqlDbType;
        partial void OnSqlDbTypeChanging(global::System.Boolean value);
        partial void OnSqlDbTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Language
        {
            get
            {
                return _Language;
            }
            set
            {
                OnLanguageChanging(value);
                ReportPropertyChanging("Language");
                _Language = StructuralObject.SetValidValue(value, false, "Language");
                ReportPropertyChanged("Language");
                OnLanguageChanged();
            }
        }
        private global::System.String _Language;
        partial void OnLanguageChanging(global::System.String value);
        partial void OnLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsLatin
        {
            get
            {
                return _IsLatin;
            }
            set
            {
                OnIsLatinChanging(value);
                ReportPropertyChanging("IsLatin");
                _IsLatin = StructuralObject.SetValidValue(value, "IsLatin");
                ReportPropertyChanged("IsLatin");
                OnIsLatinChanged();
            }
        }
        private global::System.Boolean _IsLatin;
        partial void OnIsLatinChanging(global::System.Boolean value);
        partial void OnIsLatinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JoinTable
        {
            get
            {
                return _JoinTable;
            }
            set
            {
                OnJoinTableChanging(value);
                ReportPropertyChanging("JoinTable");
                _JoinTable = StructuralObject.SetValidValue(value, false, "JoinTable");
                ReportPropertyChanged("JoinTable");
                OnJoinTableChanged();
            }
        }
        private global::System.String _JoinTable;
        partial void OnJoinTableChanging(global::System.String value);
        partial void OnJoinTableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JoinField
        {
            get
            {
                return _JoinField;
            }
            set
            {
                OnJoinFieldChanging(value);
                ReportPropertyChanging("JoinField");
                _JoinField = StructuralObject.SetValidValue(value, false, "JoinField");
                ReportPropertyChanged("JoinField");
                OnJoinFieldChanged();
            }
        }
        private global::System.String _JoinField;
        partial void OnJoinFieldChanging(global::System.String value);
        partial void OnJoinFieldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LanguageType
        {
            get
            {
                return _LanguageType;
            }
            set
            {
                OnLanguageTypeChanging(value);
                ReportPropertyChanging("LanguageType");
                _LanguageType = StructuralObject.SetValidValue(value, false, "LanguageType");
                ReportPropertyChanged("LanguageType");
                OnLanguageTypeChanged();
            }
        }
        private global::System.String _LanguageType;
        partial void OnLanguageTypeChanging(global::System.String value);
        partial void OnLanguageTypeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiledModel", Name="Rating")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rating : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rating object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="from">Initial value of the From property.</param>
        /// <param name="to">Initial value of the to property.</param>
        /// <param name="ratingValue">Initial value of the RatingValue property.</param>
        /// <param name="fromWord">Initial value of the FromWord property.</param>
        /// <param name="translation">Initial value of the Translation property.</param>
        public static Rating CreateRating(global::System.Int32 id, global::System.String from, global::System.String to, global::System.Int16 ratingValue, global::System.String fromWord, global::System.String translation)
        {
            Rating rating = new Rating();
            rating.id = id;
            rating.From = from;
            rating.to = to;
            rating.RatingValue = ratingValue;
            rating.FromWord = fromWord;
            rating.Translation = translation;
            return rating;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String From
        {
            get
            {
                return _From;
            }
            set
            {
                OnFromChanging(value);
                ReportPropertyChanging("From");
                _From = StructuralObject.SetValidValue(value, false, "From");
                ReportPropertyChanged("From");
                OnFromChanged();
            }
        }
        private global::System.String _From;
        partial void OnFromChanging(global::System.String value);
        partial void OnFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String to
        {
            get
            {
                return _to;
            }
            set
            {
                OntoChanging(value);
                ReportPropertyChanging("to");
                _to = StructuralObject.SetValidValue(value, false, "to");
                ReportPropertyChanged("to");
                OntoChanged();
            }
        }
        private global::System.String _to;
        partial void OntoChanging(global::System.String value);
        partial void OntoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 RatingValue
        {
            get
            {
                return _RatingValue;
            }
            set
            {
                OnRatingValueChanging(value);
                ReportPropertyChanging("RatingValue");
                _RatingValue = StructuralObject.SetValidValue(value, "RatingValue");
                ReportPropertyChanged("RatingValue");
                OnRatingValueChanged();
            }
        }
        private global::System.Int16 _RatingValue;
        partial void OnRatingValueChanging(global::System.Int16 value);
        partial void OnRatingValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromWord
        {
            get
            {
                return _FromWord;
            }
            set
            {
                OnFromWordChanging(value);
                ReportPropertyChanging("FromWord");
                _FromWord = StructuralObject.SetValidValue(value, false, "FromWord");
                ReportPropertyChanged("FromWord");
                OnFromWordChanged();
            }
        }
        private global::System.String _FromWord;
        partial void OnFromWordChanging(global::System.String value);
        partial void OnFromWordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Translation
        {
            get
            {
                return _Translation;
            }
            set
            {
                OnTranslationChanging(value);
                ReportPropertyChanging("Translation");
                _Translation = StructuralObject.SetValidValue(value, false, "Translation");
                ReportPropertyChanged("Translation");
                OnTranslationChanged();
            }
        }
        private global::System.String _Translation;
        partial void OnTranslationChanging(global::System.String value);
        partial void OnTranslationChanged();

        #endregion

    }

    #endregion

}
